[tool.black]
line-length = 120
target-version = ['py310']

[tool.mypy]
disable_error_code = ["no-redef"]
implicit_optional = true
warn_unreachable = true
allow_redefinition = true

[tool.ruff]
extend-exclude = [".github", "data", "logs"]
fix = true
line-length = 120
output-format = "grouped"
target-version = "py310"
